//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MedicalContext : DbContext
    {
        public MedicalContext()
            : base("name=MedicalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<ClaimStatusType> ClaimStatusTypes { get; set; }
        public virtual DbSet<FilesProccessed> FilesProccesseds { get; set; }
        public virtual DbSet<SuspiciousCode> SuspiciousCodes { get; set; }
        public virtual DbSet<View_SuspicicousCodes> View_SuspicicousCodes { get; set; }
    
        public virtual ObjectResult<usp_proccessFile_Result> usp_proccessFile(string filePathName)
        {
            var filePathNameParameter = filePathName != null ?
                new ObjectParameter("FilePathName", filePathName) :
                new ObjectParameter("FilePathName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_proccessFile_Result>("usp_proccessFile", filePathNameParameter);
        }
    }
}
